config/routes.rb
Rails.application.routes.draw do
  get 'contacts', to: 'contacts#index', as: :contacts

  get 'contacts/new', to: 'contacts#new', as: :new
  post 'contacts', to: 'contacts#create', as: :create
  
  get 'contacts/:id', to: 'contacts#show', as: :contact

  get 'contacts/:id/edit', to: 'contacts#edit', as: :edit
  patch 'contacts/:id', to: 'contacts#update', as: :update

  delete 'contacts/:id', to: 'contacts#destroy', as: :destroy
  
  # resources :contacts
  root to: 'contacts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  def index
    @contacts = Contact.all
  end
  
  def show
  end

  def new
    @contact = Contact.new
  end


  def create
    @contact = Contact.new(contact_params)
    @contact.save
   redirect_to contacts_path
  end

  def edit
  end

  def update
    @contact.update(contact_params)
    redirect_to contacts_path
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path
  end

  private

  def contact_params
    params.permit(:first_name, :last_name)
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<%= form_with(url: '/contacts', method: "post") do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <%= f.submit class:'btn btn primary', data: { confirm: 'Create a contact' } %>

<% end %>

app/views/contacts/edit.html.erb
<h1>Edit contact</h1>

<%= render 'form', contact: @contact %>


<%= link_to "Back to main page", contacts_path %>

app/views/contacts/index.html.erb
<h1>Form page</h1>
<p> Now is <%= Time.now %> </p>

<%= render 'form', contact: @contact %>

<% @contacts.each do |contact| %>
  <p>
  <%= link_to "🖱️", edit_path(contact.id), method: :edit, data:{ confirm: " Update #{contact.first_name} #{contact.last_name}?"} %>
  <%= contact.first_name %> - 
  <%= contact.last_name %> 
  [<%= contact.created_at %>]
  <%= link_to "🗑️", destroy_path(contact.id), method: :delete, data:{ confirm: " Delete #{contact.first_name} #{contact.last_name}?"} %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bigbrother</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1>Bigbrother</h1>
    <%= yield %>
  </body>
</html>